### ISSUE TITLE
Module structure exposes all methods to including base

### ISSUE THREAD

**Issue by sebastian-julius** [blinkist/transaction_logger#26]
In a scenario where the transaction logger is included into a module, the trapping of the logger doesn't work anymore:

```ruby
require "transaction_logger"

module SomeModule
  include TransactionLogger
  
  def trace_me
    puts "trace_me"
  end
  
  add_transaction_log :trace_me
end

class Test
  include SomeModule
end

test = Test.new
test.trace_me # undefined method `trap_logger' for Test:Class
```

**Comment by dinks** [comment]
Well, `TransactionLogger` is a `Module` so isnt't supposed to be an `extend`?

```ruby
module A
  def self.included(base)
    p "Included #{base}"
    base.extend ClassMethods
  end

  def self.extended(base)
    p "Extended #{base}"
    base.send :include, ClassMethods
  end

  module ClassMethods
    def gg
      p "hi"
    end
  end
end

module B
  extend A
end

class C
  include B
end

C.new.gg

```

**Comment by sebastian-julius** [comment]
Ah, true. You're right. But what I saw was the problem of the trap_logger method becoming a method on the including class. 

Do you have some clues, how we could disguise it and not inject it?

**Comment by dinks** [comment]
What do you mean by disguise? The inheritance here of the ancestors makes sure that the method is in view and gets called.

**Comment by sebastian-julius** [comment]
After a short discussion at my table, we summarized the issue as follows:
* The module definition shouldn't add any other method then `.add_transaction_log` to the base
* Every other method required for the TransactionLogger's functionality needs to be encapsulated within the GEM

@dinks @JohnBDonner any objections?

**Comment by JohnBDonner** [comment]
:+1:

**Comment by dinks** [comment]
+1
